### ISSUE TITLE
navigator is not defined error encountered when upgrading from 2.14 to 2.15

### ISSUE THREAD

**Issue by chrismatthieu** [twilio/twilio-video.js#1500]
ReferenceError: navigator is not defined
    at isSupported (/Users/christophermatthieu/Projects/unconf/grouproom/node_modules/twilio-video/es5/util/support.js:132:48)
    at Object.<anonymous> (/Users/christophermatthieu/Projects/unconf/grouproom/node_modules/twilio-video/es5/index.js:47:37)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/Users/christophermatthieu/Projects/unconf/grouproom/server/server.js:21:57)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)

**Comment by MonstraG** [comment]
Why was this closed?

I'm on Nextjs, so it probably fails on ssr. Did not fail in 2.14.0.

**Comment by charliesantos** [comment]
@MonstraG thanks for bringing this to our attention. We will take a look.

**Comment by StarpTech** [comment]
Please reopen. I have the same issue on Next.js

**Comment by charliesantos** [comment]
This has been fixed on 2.15.1.
