### ISSUE TITLE
Unable to build local version of develop or master branches

### ISSUE THREAD

**Issue by tonymccallie** [twilio/twilio-video.js#1535]
I'm trying to build a local copy of the develop branch to possibly triage the newly introduced Chrome issue #1528 but I'm getting errors with the electron deps

**Code to reproduce the issue:**

```js
git clone repo
npm install (--legacy-peer-deps and --force have the same outcome but are required to even get this far)
```

Result

```
[cut successful logs]
npm ERR! code 1
npm ERR! path /Users/tonymccallie/Sites/twilio-video.js/node_modules/electron
npm ERR! command failed
npm ERR! command sh -c node install.js
npm ERR! HTTPError: Response code 404 (Not Found) for https://github.com/electron/electron/releases/download/v9.4.4/electron-v9.4.4-darwin-arm64.zip
npm ERR!     at EventEmitter.<anonymous> (/Users/tonymccallie/Sites/twilio-video.js/node_modules/got/source/as-stream.js:35:24)
npm ERR!     at EventEmitter.emit (node:events:369:20)
npm ERR!     at module.exports (/Users/tonymccallie/Sites/twilio-video.js/node_modules/got/source/get-response.js:22:10)
npm ERR!     at ClientRequest.handleResponse (/Users/tonymccallie/Sites/twilio-video.js/node_modules/got/source/request-as-event-emitter.js:155:5)
npm ERR!     at Object.onceWrapper (node:events:476:26)
npm ERR!     at ClientRequest.emit (node:events:381:22)
npm ERR!     at ClientRequest.origin.emit (/Users/tonymccallie/Sites/twilio-video.js/node_modules/@szmarczak/http-timer/source/index.js:37:11)
npm ERR!     at HTTPParser.parserOnIncomingClient [as onIncoming] (node:_http_client:646:27)
npm ERR!     at HTTPParser.parserOnHeadersComplete (node:_http_common:129:17)
npm ERR!     at TLSSocket.socketOnData (node:_http_client:512:22)

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/tonymccallie/.npm/_logs/2021-07-28T15_57_08_191Z-debug.log
```

**Comment by makarandp0** [comment]
Hello @tonymccallie, What is OS / node version that are you using? I do not see this issue on on my MacOS Big Sur with node version v14.15.4 

Please try if updating node version helps.
Thanks,
Makarand

**Comment by tonymccallie** [comment]
I am using Node v15.14.0 on macOS 11.5.1 (m1 chip)

**Comment by makarandp0** [comment]
Unfortunately I do not have access to Mac with M1 chip it to try it out. But in the meanwhile I suggest you workaround by removing / ignoring electron dependencies, they are not needed to build the project.

**Comment by tonymccallie** [comment]
That worked, thanks. Wonder why those are in there?

**Comment by makarandp0** [comment]
Glad that it worked. We have electron dependencies because we run our integration tests against electron as one of the platforms.
