### ISSUE TITLE
Cordova app Video Chat breaks since upgrading to Android 12

### ISSUE THREAD

**Issue by karlsc** [twilio/twilio-video.js#1681]
Hi, we recently upgraded our Cordova app to work with Android 12. Since then we are getting a bunch of JS errors (only on Android device of all versions). Prior to these changes, everything was working fine. I tried tracing these errors back, but I am unsure of what they mean. I would appreciate any help or hint in the good direction.

**Expected behavior:**

Work as it was working before.

**Actual behavior:**

The errors will prevent the camera and sound feed to be shared and breaks our app completely.

Here are the errors:

```
Uncaught TypeError: _this2._target.addEventListener is not a function
    at scripts/twilio-video.min.js:52:9870
    at Array.forEach (<anonymous>)
    at NetworkMonitor.start (scripts/twilio-video.min.js:52:9831)
    at WebSocket.<anonymous> (scripts/twilio-video.min.js:50:18848)
(anonymous) @ twilio-video.min.js:52
start @ twilio-video.min.js:52
(anonymous) @ twilio-video.min.js:50

twilio-video.min.js:52 2022-01-21T17:32:08.003Z error [connect #1] createAndOffer() failed: TwilioError: Media connection failed or Media activity ceased
    at MediaConnectionError.TwilioError (scripts/twilio-video.min.js:54:13742)
    at new MediaConnectionError (scripts/twilio-video.min.js:54:9697)
    at PeerConnectionManager._getOrCreate (scripts/twilio-video.min.js:46:17586)
    at scripts/twilio-video.min.js:46:19108
log @ twilio-video.min.js:52
error @ twilio-video.min.js:52
(anonymous) @ twilio-video.min.js:44

twilio-video.min.js:54 Uncaught (in promise) TwilioError: Media connection failed or Media activity ceased
    at MediaConnectionError.TwilioError (scripts/twilio-video.min.js:54:13742)
    at new MediaConnectionError (scripts/twilio-video.min.js:54:9697)
    at PeerConnectionManager._getOrCreate (scripts/twilio-video.min.js:46:17586)
    at scripts/twilio-video.min.js:46:19108
TwilioError @ twilio-video.min.js:54
MediaConnectionError @ twilio-video.min.js:54
_getOrCreate @ twilio-video.min.js:46
(anonymous) @ twilio-video.min.js:46

twilio-video.min.js:52 Uncaught (in promise) TypeError: _this3._target.removeEventListener is not a function
    at scripts/twilio-video.min.js:52:10017
    at Array.forEach (<anonymous>)
    at NetworkMonitor.stop (scripts/twilio-video.min.js:52:9978)
    at TwilioConnection._close (scripts/twilio-video.min.js:50:17464)
    at TwilioConnection.close (scripts/twilio-video.min.js:50:25244)
    at TwilioConnectionTransport.disconnect (scripts/twilio-video.min.js:48:5088)
    at scripts/twilio-video.min.js:44:8946
(anonymous) @ twilio-video.min.js:52
stop @ twilio-video.min.js:52
_close @ twilio-video.min.js:50
close @ twilio-video.min.js:50
disconnect @ twilio-video.min.js:48
(anonymous) @ twilio-video.min.js:44

twilio-video.min.js:54 Uncaught (in promise) TwilioError: Media connection failed or Media activity ceased
    at MediaConnectionError.TwilioError (scripts/twilio-video.min.js:54:13742)
    at new MediaConnectionError (scripts/twilio-video.min.js:54:9697)
    at PeerConnectionManager._getOrCreate (scripts/twilio-video.min.js:46:17586)
    at scripts/twilio-video.min.js:46:19108
TwilioError @ twilio-video.min.js:54
MediaConnectionError @ twilio-video.min.js:54
_getOrCreate @ twilio-video.min.js:46
(anonymous) @ twilio-video.min.js:46

twilio-video.min.js:52 Uncaught TypeError: _this3._target.removeEventListener is not a function
    at scripts/twilio-video.min.js:52:10017
    at Array.forEach (<anonymous>)
    at NetworkMonitor.stop (scripts/twilio-video.min.js:52:9978)
    at TwilioConnection._close (scripts/twilio-video.min.js:50:17464)
    at WebSocket.<anonymous> (scripts/twilio-video.min.js:50:18452)
```

**Software versions:**

 - [ ] Browser(s):
 - [x] Operating System: Android
 - [x] twilio-video.js: 2.11.0 & ^2.18.0
 - [x] Third-party libraries (e.g., Angular, React, etc.): Cordova, AngularJS, React

**Comment by charliesantos** [comment]
Hi @karlsc ,
Sorry to hear you are having this issue. Unfortunately, we currently don't have an official support for webviews. But I'm happy to help as time permits. Do you have the entire error logs? The logs you posted seems truncated.

**Comment by nabilzhafri** [comment]
@charliesantos i seem to encounter same error. wondering if you have any update on this issue? works fine on ios, but not android

**Comment by charliesantos** [comment]
Closing due to inactivity and we currently don't have official support for Android Webviews per my comment above.
