### ISSUE TITLE
TwilioError: The track kind is not supported by the Room

### ISSUE THREAD

**Issue by deekshaa8** [twilio/twilio-video.js#1753]
Hi,

I'm working on this github url: (https://github.com/dcanonmolina/OnlyScreenShareVideoProject)

But while running the code locally, Im getting this issue:TwilioError: The track kind is not supported by the Room
    at RoomTrackKindNotSupportedError.TwilioError [as constructor] (twilio-video.min.js:53:22759)
    at new RoomTrackKindNotSupportedError (twilio-video.min.js:53:10363)
    at createTwilioError (twilio-video.min.js:52:26090)
    at LocalTrackPublicationV2.update (twilio-video.min.js:44:31502)
    at LocalParticipantV2.<anonymous> (twilio-video.min.js:44:27871)
    at Array.forEach (<anonymous>)
    at LocalParticipantV2.update (twilio-video.min.js:44:27719)
    at RoomV2._update (twilio-video.min.js:47:22958)
    at TwilioConnectionTransport.emit (twilio-video.min.js:56:17108)
    at TwilioConnection.handleMessage (twilio-video.min.js:48:18280)

checked in all the browsers. Still the same issue

**Comment by PikaJoyce** [comment]
Hi @deekshaa8,

Thanks for opening this issue with us. 

Could you please try out our screen share [QuickStart example](https://github.com/twilio/video-quickstart-js/tree/master/examples/screenshare/src)? 

Some debugging suggestions, I believe that the issue may be coming from [this line](https://github.com/dcanonmolina/OnlyScreenShareVideoProject/blob/7fbbcd2b36e7430ab65e90f95088a577204c7d38/public/index.js#L29) when [publishVideoTrack](https://github.com/dcanonmolina/OnlyScreenShareVideoProject/blob/7fbbcd2b36e7430ab65e90f95088a577204c7d38/public/index.js#L49) gets called. Could you please ensure that the `screenTrack` here is defined prior to publishing to the room. Potentially, you are passing in a track that does not exist (yet) is what I am thinking.

Best,
Joyce

**Comment by PikaJoyce** [comment]
Closing due to inactivity.
