### ISSUE TITLE
Local participant disconnected error after using EndCallButton to disconnect

### ISSUE THREAD

**Issue by cindyloo** [twilio/twilio-video.js#1855]
code from Twilio React sample app
```
export default function EndCallButton(props: { className?: string }) {
  const classes = useStyles();
  const vRoom = useRoomState();
  const handleClick = (e, vRoom, room) => {
    if (!isEmpty(vRoom)) {
      if (room.localParticipant && vRoom === "connected") {
        try {
          room && room.localParticipant.state === 'connected' && room.disconnect()
        } catch (e) {
          console.log("endcall button caught error");
        }
      } else {
        console.log("Error participant already disconnected");
      }
    }
  };

  //useEffect(() => {
  //}, vRoom);
  return (
    <Button
      onClick={e => handleClick(e, vRoom, props.room)}
      className={clsx(classes.button, props.className)}
      data-cy-disconnect
    >
      Disconnect
    </Button>
  );
}
```

**Expected behavior:**

I'd expect to disconnect and receive no error

TODO

```Uncaught (in promise) Error: LocalParticipant disconnected
    at eval (room.js?5fe1:244:1)
    at Map.forEach (<anonymous>)
    at RoomV2._disconnect (room.js?5fe1:243:1)
    at RoomSignaling.disconnect (room.js?b982:204:1)
    at Room.disconnect (room.js?47f1:174:1)
    at handleClick (EndCallButton.tsx?bb64:29:71)
    at onClick (EndCallButton.tsx?bb64:43:21)
    at HTMLUnknownElement.callCallback (react-dom.development.js?ac89:188:1)
    at Object.invokeGuardedCallbackDev (react-dom.development.js?ac89:237:1)
    at invokeGuardedCallback (react-dom.development.js?ac89:292:1)
    at invokeGuardedCallbackAndCatchFirstError (react-dom.development.js?ac89:306:1)
    at executeDispatch (react-dom.development.js?ac89:389:1)
    at executeDispatchesInOrder (react-dom.development.js?ac89:414:1)
    at executeDispatchesAndRelease (react-dom.development.js?ac89:3278:1)
    at executeDispatchesAndReleaseTopLevel (react-dom.development.js?ac89:3287:1)
    at forEachAccumulated (react-dom.development.js?ac89:3259:1)
    at runEventsInBatch (react-dom.development.js?ac89:3304:1)
    at runExtractedPluginEventsInBatch (react-dom.development.js?ac89:3514:1)
    at handleTopLevel (react-dom.development.js?ac89:3558:1)
    at batchedEventUpdates$1 (react-dom.development.js?ac89:21871:1)
    at batchedEventUpdates (react-dom.development.js?ac89:795:1)
    at dispatchEventForLegacyPluginEventSystem (react-dom.development.js?ac89:3568:1)
    at attemptToDispatchEvent (react-dom.development.js?ac89:4267:1)
    at dispatchEvent (react-dom.development.js?ac89:4189:1)
    at unstable_runWithPriority (scheduler.development.js?c964:653:1)
    at runWithPriority$1 (react-dom.development.js?ac89:11039:1)
    at discreteUpdates$1 (react-dom.development.js?ac89:21887:1)
    at discreteUpdates (react-dom.development.js?ac89:806:1)
    at dispatchDiscreteEvent (react-dom.development.js?ac89:4168:1)
```

**Software versions:**

 - [ ] Browser(s): Chrome 103
 - [ ] Operating System: Mac OS Big Sur
 - [ ] twilio-video.js: 2.21.2 and 2.22.0
React

**Comment by cindyloo** [comment]
<img width="954" alt="Screen Shot 2022-08-15 at 6 35 51 AM" src="https://user-images.githubusercontent.com/659092/184635576-56fcd2dc-d18b-4751-8bee-731b928ab85b.png">

**Comment by cindyloo** [comment]
debug logs from Twilio if helpful:

```
2022-08-16T19:17:13.257Z debug [RemoteAudioTrack #18: MT278d00ef872f90ab57e2ab75305d1a54] Ended
log.js?a324:167 2022-08-16T19:17:13.257Z debug [RemoteVideoTrack #19: MTc7382970360af265e1538fc0712b3625] Ended
log.js?a324:167 2022-08-16T19:17:13.258Z debug [RemoteVideoTrack #20: MT7d37ab7b378a74548b748c1641b52d1c] Ended
log.js?a324:167 2022-08-16T19:17:13.258Z info [MediaSignaling #1:network_quality] Tearing down
log.js?a324:167 2022-08-16T19:17:13.259Z info [MediaSignaling #3:publisher_hints] Tearing down
log.js?a324:167 2022-08-16T19:17:13.259Z info [MediaSignaling #0:active_speaker] Tearing down
log.js?a324:167 2022-08-16T19:17:13.259Z info [MediaSignaling #5:track_switch_off] Tearing down
log.js?a324:167 2022-08-16T19:17:13.260Z info [MediaSignaling #2:render_hints] Tearing down
log.js?a324:167 2022-08-16T19:17:13.260Z info [MediaSignaling #4:track_priority] Tearing down
2room.js:255 Uncaught (in promise) Error: LocalParticipant disconnected
    at eval (webpack-internal:///./node_modules/twilio-video/es5/signaling/v2/room.js:255:42)
    at Map.forEach (<anonymous>)
    at RoomV2._disconnect (webpack-internal:///./node_modules/twilio-video/es5/signaling/v2/room.js:254:38)
    at RoomSignaling.disconnect (webpack-internal:///./node_modules/twilio-video/es5/signaling/room.js:204:21)
    at Room.disconnect (webpack-internal:///./node_modules/twilio-video/es5/room.js:178:25)
    at disconnect (webpack-internal:///./src/components/VideoProvider/useRoom/useRoom.tsx:71:32)
eval @ room.js:255
RoomV2._disconnect @ room.js:254
RoomSignaling.disconnect @ room.js:204
Room.disconnect @ room.js:178
disconnect @ useRoom.tsx:71
index.tsx?72be:115 VideoProvider {type: 'none'}
```

**Comment by PikaJoyce** [comment]
Hi @cindyloo,

Thank you for opening this issue with us. It seems like this is an issue with the twilio-video react app. I'll be transferring this over to our wonderful folks there! 

Best,
Joyce
