### ISSUE TITLE
Unhandled rejection CONFIGURATION_ERROR. 

### ISSUE THREAD

**Issue by nikolaylukyanchuk** [twilio/twilio-video.js#55]
Hi. Have some problems.

On local machine everything works well. But when I do a production build and open a page with video conversation, I got this error.

Using lib from cdn
//media.twiliocdn.com/sdk/js/video/v1/twilio-video.min.js

```
Unhandled rejection CONFIGURATION_ERROR: Invalid value "user_demo@XXx51c1dd4352e5395d3db20ff177626c0.endpoint.twilio.com" for parameter "uri"
    at http://media.twiliocdn.com/sdk/js/video/releases/1.0.0-beta4/twilio-video.min.js:95:16878
    at Object.r.80 (http://media.twiliocdn.com/sdk/js/video/releases/1.0.0-beta4/twilio-video.min.js:95:16905)
    at s (http://media.twiliocdn.com/sdk/js/video/releases/1.0.0-beta4/twilio-video.min.js:89:280)
    at http://media.twiliocdn.com/sdk/js/video/releases/1.0.0-beta4/twilio-video.min.js:89:331
    at module.exports (http://media.twiliocdn.com/sdk/js/video/releases/1.0.0-beta4/twilio-video.min.js:97:18349)
    at Object.<anonymous> (http://media.twiliocdn.com/sdk/js/video/releases/1.0.0-beta4/twilio-video.min.js:91:31288)
    at Object.r.38.sip.js/src/SIP (http://media.twiliocdn.com/sdk/js/video/releases/1.0.0-beta4/twilio-video.min.js:91:31434)
    at s (http://media.twiliocdn.com/sdk/js/video/releases/1.0.0-beta4/twilio-video.min.js:89:280)
    at http://media.twiliocdn.com/sdk/js/video/releases/1.0.0-beta4/twilio-video.min.js:89:331
    at Object.r.37.../../sip (http://media.twiliocdn.com/sdk/js/video/releases/1.0.0-beta4/twilio-video.min.js:91:24169)
From previous event:
```

does any one can help?

**Comment by nikolaylukyanchuk** [comment]
fixed when move to not minimized version of the lib

**Comment by markandrus** [comment]
Hi @nikolaylukyanchuk,

I believe you hit the same error as [here](https://github.com/twilio/twilio-video.js/issues/50). The minified beta4 release (and previous minified builds) use special characters that require you to specify a charset, either in

* The Content-Type header via your HTTP server, or
* A &lt;meta&gt; tag.

We'll ensure that future minified releases will not use these characters. Sorry you ran into this!

Mark
