### ISSUE TITLE
npm/yarn install issue

### ISSUE THREAD

**Issue by gniquil** [twilio/twilio-video.js#96]
The error occurs whenever I try to `yarn add` another lib while having twilio-video installed. The work around for me right now is first remove twilio-video, add the new lib, then re-add twilio-video

 - [x] I have verified that the issue occurs with the latest twilio-video.js release and is not marked as a known issue in the [CHANGELOG.md](https://github.com/twilio/twilio-video.js/blob/master/CHANGELOG.md).
 - [x] I reviewed the [Common Issues](https://github.com/twilio/twilio-video.js/blob/master/COMMON_ISSUES.md) and open GitHub issues and verified that this report represents a potentially new issue.
 - [x] I verified that the [Quickstart](https://github.com/twilio/video-quickstart-js) application works in my environment.

**Code to reproduce the issue:**

Make sure you have twilio-video installed in package.json. Then add some lib. It should fail with error specified below.

**Expected behavior:**

Install correctly

**Actual behavior:**

The following is the last bit from the yarn-error.log

```
Trace: 
  TypeError: Cannot read property 'split' of undefined
      at Function.parseRefs (/usr/local/Cellar/yarn/0.16.1/libexec/lib/node_modules/yarn/lib/util/git.js:439:20)
      at /usr/local/Cellar/yarn/0.16.1/libexec/lib/node_modules/yarn/lib/resolvers/exotics/hosted-git-resolver.js:138:50
      at next (native)
      at step (/usr/local/Cellar/yarn/0.16.1/libexec/lib/node_modules/yarn/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
      at /usr/local/Cellar/yarn/0.16.1/libexec/lib/node_modules/yarn/node_modules/babel-runtime/helpers/asyncToGenerator.js:28:20
      at process._tickCallback (internal/process/next_tick.js:103:7)

```

**Software versions:**

 - [x] Browser(s): Any
 - [x] Operating System: OSX 10.12.4
 - [x] twilio-video.js: 1.0.0
 - [ ] Third-party libraries (e.g., Angular, React, etc.):

**Comment by markandrus** [comment]
Hi @gniquil,

Thanks for the report! It looks like you are using yarn 0.16.1? Can you retry with yarn 0.23.0? Here's a little test script I wrote. Does it work for you?

```sh
#!/bin/sh
set -e
mkdir test-yarn-and-twilio-video
cd test-yarn-and-twilio-video
yarn --version
yes | yarn init
yarn add d3
yarn add twilio-video
yarn add cheerio
node -e "console.log(require('twilio-video').version)"
cd ..
rm -rf test-yarn-and-twilio-video
```

and here is the output for me:

```
0.23.3
yarn init v0.23.3
question name (test-yarn-and-twilio-video): y
question version (1.0.0): y
question description: y
question entry point (index.js): y
question repository url: y
question author: y
question license (MIT): y
success Saved package.json
✨  Done in 0.50s.
yarn add v0.23.3
info No lockfile found.
warning y@y: License should be a valid SPDX license expression
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 📃  Building fresh packages...
success Saved lockfile.
success Saved 36 new dependencies.
├─ commander@2.9.0
├─ d3-array@1.2.0
├─ d3-axis@1.0.6
├─ d3-brush@1.0.4
├─ d3-chord@1.0.4
├─ d3-collection@1.0.3
├─ d3-color@1.0.3
├─ d3-dispatch@1.0.3
├─ d3-drag@1.0.4
├─ d3-dsv@1.0.5
├─ d3-ease@1.0.3
├─ d3-force@1.0.6
├─ d3-format@1.2.0
├─ d3-geo@1.6.3
├─ d3-hierarchy@1.1.4
├─ d3-interpolate@1.1.4
├─ d3-path@1.0.5
├─ d3-polygon@1.0.3
├─ d3-quadtree@1.0.3
├─ d3-queue@3.0.5
├─ d3-random@1.0.3
├─ d3-request@1.0.5
├─ d3-scale@1.0.5
├─ d3-selection@1.0.5
├─ d3-shape@1.0.6
├─ d3-time-format@2.0.5
├─ d3-time@1.0.6
├─ d3-timer@1.0.5
├─ d3-transition@1.0.4
├─ d3-voronoi@1.1.2
├─ d3-zoom@1.1.4
├─ d3@4.8.0
├─ graceful-readlink@1.0.1
├─ iconv-lite@0.4.17
├─ rw@1.3.3
└─ xmlhttprequest@1.8.0
warning y@y: License should be a valid SPDX license expression
✨  Done in 1.47s.
yarn add v0.23.3
warning y@y: License should be a valid SPDX license expression
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 📃  Building fresh packages...
success Saved lockfile.
success Saved 9 new dependencies.
├─ options@0.0.6
├─ pegjs@0.8.0
├─ promiscuous@0.6.0
├─ safe-buffer@5.0.1
├─ sip.js@0.7.5
├─ twilio-video@1.0.0
├─ ultron@1.1.0
├─ ws@2.3.1
└─ xmlhttprequest@1.8.0
warning y@y: License should be a valid SPDX license expression
✨  Done in 1.73s.
yarn add v0.23.3
warning y@y: License should be a valid SPDX license expression
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 📃  Building fresh packages...
success Saved lockfile.
success Saved 32 new dependencies.
├─ boolbase@1.0.0
├─ buffer-shims@1.0.0
├─ cheerio@0.22.0
├─ core-util-is@1.0.2
├─ css-select@1.2.0
├─ css-what@2.1.0
├─ dom-serializer@0.1.0
├─ domelementtype@1.3.0
├─ domhandler@2.3.0
├─ domutils@1.5.1
├─ entities@1.1.1
├─ htmlparser2@3.9.2
├─ inherits@2.0.3
├─ isarray@1.0.0
├─ lodash.assignin@4.2.0
├─ lodash.bind@4.2.1
├─ lodash.defaults@4.2.0
├─ lodash.filter@4.6.0
├─ lodash.flatten@4.4.0
├─ lodash.foreach@4.5.0
├─ lodash.map@4.6.0
├─ lodash.merge@4.6.0
├─ lodash.pick@4.4.0
├─ lodash.reduce@4.6.0
├─ lodash.reject@4.6.0
├─ lodash.some@4.6.0
├─ nth-check@1.0.1
├─ process-nextick-args@1.0.7
├─ readable-stream@2.2.9
├─ sip.js@0.7.5
├─ string_decoder@1.0.0
└─ util-deprecate@1.0.2
warning y@y: License should be a valid SPDX license expression
✨  Done in 1.30s.
1.0.0
```

**Comment by gniquil** [comment]
Thanks! Self-updating yarn worked perfectly (tried your script failed with the older version and went fine after). I am closing the issue now.
